CREATE TABLE IF NOT EXISTS tipos_servicio (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255) NOT NULL,
    costo_base DOUBLE NOT NULL
);
