spring.application.name=bff
server.port=8085

usuarios.service.url=${USUARIOS_URL:http://localhost:8081}
computador.service.url=${COMPUTADOR_URL:http://localhost:8080}
tiposervicio.service.url=${TIPOSERVICIO_URL:http://localhost:8082}
mantencion.service.url=${MANTENCION_URL:http://localhost:8084}
