spring.application.name=bff
server.port=8085

customer.service.url=${USUARIOS_URL:http://localhost:8081}
computer.service.url=${COMPUTADOR_URL:http://localhost:8080}
servicetype.service.url=${TIPOSERVICIO_URL:http://localhost:8082}
maintenance.service.url=${MANTENCION_URL:http://localhost:8084}

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-hours=24
