spring.application.name=bff
server.port=8085

usuarios.service.base-url=${USUARIOS_URL:http://localhost:8081}/api/auth

security.jwt.secret=${JWT_SECRET:claveSecretaMuySeguraParaJWT2024!!}
security.jwt.expiration-hours=24
